version: '2'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: yarn start:dev
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8001:8001'
